const mongoose = require('mongoose');

const RoomSchema = new mongoose.Schema({
    users:{
        type:Array,
        default:[]
    },
    task:{
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Task'
    },
    experimentalCondition:{
        type:String
    },
    stage:{
        type:String
    },
    status:{
        type:String,
        default:'open'
    },
    currentRound:{
        type:Number
    },
    roundEnds:{
        type:Date
    },
    timeLimit:{
        type:Number
    },
    currentResponder:{
        type:String
    },
    currentQuestionIndex:{
        type:Number
    },
    questionsPerRound:{
        type:Number
    },
    currentResponseTries:{
        type:Number
    },
    currentResponseComplete:{
        type:Boolean
    },
    currentPoints:{
        type:Number,
        default:0
    },
    answerPoints:{
        type:Number,
        default:0
    },
    messagePoints:{
        type:Number,
        default:0
    },
    pointsPossible:{
        type:Number
    },
    chatUpdated:{
        type:Date,
        default:Date.now()
    },
    chat:{
        type:Array,
        default:[]
    },
    dateCreated:{
        type:Date,
        default:Date.now()
    },
    illegalWords:{
        type:Array,
        default:[]
    },
    exceptionWords:{
        type:Array,
        default:[]
    },
    setLemmas:{
        type:Array,
        default:[]
    },
    sectionLemmas:{
        type:Array,
        default:[]
    },
    setStart:{
        type:Number
    },
    setEnd:{
        type:Number
    },
    sectionStart:{
        type:Number
    },
    sectionEnd:{
        type:Number
    },
    sectionSynonyms:{
        type:Object,
        default:{}
    },
    synonymsUsed:{
        type:Array,
        default:[]     
    },
    synonymRewards:{
        type:Object,
        default:{}    
    },
    feedback:{
        type:Array,
        default:[]
    },
    log:{
        type:Array,
        default:[]
    },
    sequence:{
        type:Array,
        sequence:[]
    }
});

module.exports = RoomSchema;
